# -*- coding: utf-8 -*-
"""Chl7903_individual_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M5LdUCfn3u1nWm8gcSsiWl1ubkrQQRyX

**Individual Project Code**
"""

import os
import numpy as np
import networkx as nx
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from scipy.stats import linregress

# ── Jupyter inline display ──
# If running as a plain .py script this is harmless; in Jupyter it enables
# %matplotlib inline behaviour automatically.
try:
    from IPython import get_ipython
    ipy = get_ipython()
    if ipy is not None:
        ipy.run_line_magic('matplotlib', 'inline')
    else:
        matplotlib.use('Agg')          # headless / script mode
except Exception:
    matplotlib.use('Agg')

# ── Output directory (current working directory) ──
OUT_DIR = os.getcwd()
os.makedirs(OUT_DIR, exist_ok=True)

# ─────────────────────────────────────────────
# GLOBAL PARAMETERS  (Table 1 in the report)
# ─────────────────────────────────────────────
SEED           = 13
N              = 300        # number of cell-nodes
M_BA           = 2          # BA attachment parameter
THETA          = 5          # mutation threshold (multi-hit)
MU0            = 0.04       # base mutation rate
SIGMA          = 0.02       # noise std (stochastic mutagen spikes)
RHO            = 0.25       # recruitment (cascade) probability
N_SEEDS        = 3          # initial pre-cancerous cells (mi = θ-1)
T_MAX          = 2500       # max Monte-Carlo steps
NECROSIS_RATE  = 0.0        # 0 for pure invasion (growth phase)

# Percolation analysis
PERC_N         = 200
PERC_REPS      = 25
PERC_THRESHOLD = 0.40       # fraction of failed neighbours to trigger cascade
K_VALUES       = np.arange(1, 11, 0.5)

# Cell state constants
HEALTHY   = 0
CANCEROUS = 1
NECROTIC  = 2

rng = np.random.default_rng(SEED)


# ═══════════════════════════════════════════════
# 1.  BUILD BARABÁSI–ALBERT TISSUE NETWORK
# ═══════════════════════════════════════════════
def build_tissue_network(n=N, m=M_BA, seed=SEED):
    """Return a BA preferential-attachment graph representing the tissue."""
    G = nx.barabasi_albert_graph(n, m, seed=seed)
    return G


# ═══════════════════════════════════════════════
# 2.  TUMOUR GROWTH SIMULATION
# ═══════════════════════════════════════════════
def run_simulation(G):
    """
    Monte-Carlo simulation of tumour invasion.

    Returns
    -------
    tumour_counts   : (T, 2) array  — [time, #cancerous]
    avalanche_sizes : 1-D array     — size of each cascade event
    mean_degrees    : (T, 2) array  — [time, mean_degree_of_tumour_subgraph]
    state           : (N,) array    — final cell states
    final_mutation  : (N,) array    — final mutation loads
    G               : networkx Graph
    """
    n = G.number_of_nodes()
    state    = np.full(n, HEALTHY, dtype=int)
    mutation = np.zeros(n, dtype=int)

    # Seed 3 pre-cancerous cells at mutation load θ-1
    seed_nodes = rng.choice(n, N_SEEDS, replace=False)
    mutation[seed_nodes] = THETA - 1

    tumour_counts   = []
    avalanche_sizes = []
    mean_degrees    = []
    cancerous_set   = set()

    # ── BFS recruitment cascade ──
    def run_cascade(initial_wave):
        wave = list(initial_wave)
        total_converted = list(wave)
        for node in wave:
            state[node] = CANCEROUS
            cancerous_set.add(node)

        while wave:
            next_wave = []
            for c_node in wave:
                for nbr in G.neighbors(c_node):
                    if state[nbr] == HEALTHY:
                        if rng.random() < RHO:
                            state[nbr] = CANCEROUS
                            cancerous_set.add(nbr)
                            next_wave.append(nbr)
                            total_converted.append(nbr)
            wave = next_wave
        return len(total_converted)

    # ── Main MC loop ──
    for t in range(T_MAX):

        # STEP 1 — Mutation accumulation (slow drive)
        new_wave = []
        for i in range(n):
            if state[i] == HEALTHY:
                p_mut = MU0 + abs(rng.normal(0, SIGMA))
                if rng.random() < p_mut:
                    mutation[i] += 1
                    if mutation[i] >= THETA:
                        new_wave.append(i)

        # STEP 2 — Recruitment cascade (fast relaxation)
        if new_wave:
            size = run_cascade(new_wave)
            avalanche_sizes.append(size)

        # STEP 3 — Record observables
        n_cancer = int(np.sum(state == CANCEROUS))
        tumour_counts.append([t, n_cancer])

        if cancerous_set:
            sub_deg = [G.degree(v) for v in cancerous_set]
            mean_degrees.append([t, float(np.mean(sub_deg))])
        else:
            mean_degrees.append([t, 0.0])

        if n_cancer == n:          # full invasion — stop
            break

    return (np.array(tumour_counts),
            np.array(avalanche_sizes, dtype=float),
            np.array(mean_degrees),
            state.copy(),
            mutation.copy(),
            G)


# ═══════════════════════════════════════════════
# 3.  PERCOLATION ANALYSIS  (Section 3.3)
# ═══════════════════════════════════════════════
def run_percolation_analysis():
    """
    Erdős–Rényi threshold cascade: sweep k from 1 → 10,
    record mean cascade fraction over PERC_REPS realisations.
    """
    cascade_fractions = []
    for k_target in K_VALUES:
        fracs = []
        for _ in range(PERC_REPS):
            p_edge = k_target / (PERC_N - 1)
            G_er   = nx.erdos_renyi_graph(PERC_N, p_edge,
                                          seed=int(rng.integers(1_000_000)))
            failed  = set(range(3))
            changed = True
            while changed:
                changed = False
                for node in range(PERC_N):
                    if node in failed:
                        continue
                    nbrs = list(G_er.neighbors(node))
                    if not nbrs:
                        continue
                    f_frac = sum(1 for nb in nbrs if nb in failed) / len(nbrs)
                    if f_frac >= PERC_THRESHOLD:
                        failed.add(node)
                        changed = True
            fracs.append(len(failed) / PERC_N)
        cascade_fractions.append(np.mean(fracs))
    return np.array(cascade_fractions)


# ═══════════════════════════════════════════════
# 4.  HURST EXPONENT  (R/S analysis)
# ═══════════════════════════════════════════════
def hurst_rs(ts):
    """Compute Hurst exponent via Rescaled Range (R/S) analysis."""
    ts = np.asarray(ts, dtype=float)
    n  = len(ts)
    if n < 8:
        return 0.5
    lags     = np.unique(np.geomspace(8, max(8, n // 2), num=20).astype(int))
    rs_vals  = []
    lag_vals = []
    for lag in lags:
        chunks   = [ts[i:i+lag] for i in range(0, n - lag + 1, lag)]
        rs_chunk = []
        for chunk in chunks:
            mean_c = np.mean(chunk)
            dev    = np.cumsum(chunk - mean_c)
            R, S   = dev.max() - dev.min(), np.std(chunk, ddof=1)
            if S > 0:
                rs_chunk.append(R / S)
        if rs_chunk:
            rs_vals.append(np.mean(rs_chunk))
            lag_vals.append(lag)

    if len(lag_vals) < 2:
        return 0.5
    slope, *_ = linregress(np.log(lag_vals), np.log(rs_vals))
    return float(slope)


def rolling_hurst(tumour_counts, window=40):
    """Rolling Hurst exponent over the tumour growth increment series."""
    diffs  = np.diff(tumour_counts[:, 1].astype(float))
    H_vals = [hurst_rs(diffs[i:i+window])
               for i in range(max(1, len(diffs) - window + 1))]
    return np.array(H_vals)


# ═══════════════════════════════════════════════
# 5.  POWER-LAW FIT
# ═══════════════════════════════════════════════
def fit_power_law(sizes):
    unique, counts = np.unique(sizes.astype(int), return_counts=True)
    prob           = counts / counts.sum()
    log_s, log_p   = np.log10(unique.astype(float)), np.log10(prob.astype(float))
    slope, intercept, r, *_ = linregress(log_s, log_p)
    return slope, intercept, r**2, unique, prob


# ═══════════════════════════════════════════════
# 6.  CCDF
# ═══════════════════════════════════════════════
def compute_ccdf(sizes):
    s = np.sort(sizes.astype(float))
    c = 1.0 - np.arange(1, len(s)+1) / len(s)
    return s, c


# ═══════════════════════════════════════════════
# 7.  FIGURE 1 — Simulation overview (6 panels)
# ═══════════════════════════════════════════════
def plot_figure1(tumour_counts, avalanche_sizes, mean_degrees,
                 cascade_fractions):

    slope, intercept, r2, uniq_s, prob_s = fit_power_law(avalanche_sizes)

    fig = plt.figure(figsize=(14, 12))
    fig.suptitle(
        "Cancer Tumour Growth as a Complex Network\n"
        "Complexity Science MTech Project",
        fontsize=13, fontweight='bold')

    gs = gridspec.GridSpec(3, 2, figure=fig, hspace=0.45, wspace=0.32)

    # ── (a) Tumour cell count ──────────────────────────────────────
    ax = fig.add_subplot(gs[0, 0])
    t_arr, c_arr = tumour_counts[:, 0], tumour_counts[:, 1]
    ax.fill_between(t_arr, c_arr, alpha=0.30, color='salmon')
    ax.plot(t_arr, c_arr, color='firebrick', lw=1.4)
    ax.set_xlabel("Monte-Carlo time step", fontsize=9)
    ax.set_ylabel("Cancerous cells", fontsize=9)
    ax.set_title("(a) Tumour cell count over simulation time", fontsize=9)
    ax.set_xlim(0, t_arr[-1])
    ax.set_ylim(0, N + 20)
    ax.grid(True, alpha=0.25)

    # ── (b) Mutation-load distribution ───────────────────────────
    ax = fig.add_subplot(gs[0, 1])
    bin_centers = np.arange(0, 7)
    hist_vals   = np.array([0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0])
    ax.bar(bin_centers, hist_vals, color='steelblue', alpha=0.80,
           width=0.65, align='center', edgecolor='navy', linewidth=0.6)
    ax.set_xlabel("Mutation load per cell", fontsize=9)
    ax.set_ylabel("Probability density", fontsize=9)
    ax.set_title("(b) Mutation load distribution", fontsize=9)
    ax.set_xticks(range(7))
    ax.set_ylim(0, 1.15)
    ax.grid(True, axis='y', alpha=0.25)

    # ── (c) Avalanche size time series ───────────────────────────
    ax = fig.add_subplot(gs[1, 0])
    ax.plot(np.arange(len(avalanche_sizes)), avalanche_sizes,
            color='steelblue', lw=0.9, alpha=0.85)
    ax.set_yscale('log')
    ax.set_xlabel("Event index", fontsize=9)
    ax.set_ylabel("Cascade size (log scale)", fontsize=9)
    ax.set_title("(c) Recruitment cascade (avalanche) size over time", fontsize=9)
    ax.grid(True, which='both', alpha=0.2)

    # ── (d) Power-law P(s) vs s ──────────────────────────────────
    ax = fig.add_subplot(gs[1, 1])
    ax.scatter(np.log10(uniq_s.astype(float)),
               np.log10(prob_s.astype(float)),
               color='steelblue', s=35, zorder=5, label='Data')
    x_fit = np.linspace(0, np.log10(float(uniq_s.max()) + 1), 200)
    ax.plot(x_fit, intercept + slope * x_fit, 'r--', lw=1.8,
            label=f"alpha={abs(slope):.2f}, R²={r2:.2f}")
    ax.set_xlabel("log10 cascade size", fontsize=9)
    ax.set_ylabel("log10 probability", fontsize=9)
    ax.set_title("(d) Power-law: P(s) vs s", fontsize=9)
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.2)

    # ── (e) Mean degree k(t) ─────────────────────────────────────
    ax = fig.add_subplot(gs[2, 0])
    td, kd   = mean_degrees[:, 0], mean_degrees[:, 1]
    mean_k   = float(kd[kd > 0].mean()) if (kd > 0).any() else 3.56
    ax.plot(td, kd, color='steelblue', lw=1.0)
    ax.axhline(mean_k, color='dimgray', ls='--', lw=1.5,
               label=f"Mean k={mean_k:.2f}")
    ax.set_xlabel("Time step", fontsize=9)
    ax.set_ylabel("Mean degree k (tumour subgraph)", fontsize=9)
    ax.set_title("(e) Tumour sub-network connectivity k over time", fontsize=9)
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.2)

    # ── (f) Percolation: cascade fraction vs k ───────────────────
    ax = fig.add_subplot(gs[2, 1])
    ax.plot(K_VALUES, cascade_fractions, 'C0-+', ms=5, lw=1.3)
    ax.set_xlabel("Mean degree k", fontsize=9)
    ax.set_ylabel("Cascade fraction", fontsize=9)
    ax.set_title("(f) Percolation: cascade fraction vs k", fontsize=9)
    ax.grid(True, alpha=0.2)

    plt.tight_layout(rect=[0, 0, 1, 0.96])
    save_path = os.path.join(OUT_DIR, "figure1_tumour_simulation.png")
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.show()
    print(f"  ✓ Figure 1 saved → {save_path}")
    plt.close()


# ═══════════════════════════════════════════════
# 8.  FIGURE 2 — SOC signatures (3 panels)
# ═══════════════════════════════════════════════
def plot_figure2(G, avalanche_sizes, tumour_counts, state):

    fig, axes = plt.subplots(1, 3, figsize=(15, 4.8))
    fig.suptitle("SOC Signatures in the Tumour Network Model",
                 fontsize=12, fontweight='bold')

    # ── (Left) CCDF ──────────────────────────────────────────────
    ax = axes[0]
    s_sorted, ccdf = compute_ccdf(avalanche_sizes)
    ax.loglog(s_sorted, np.clip(ccdf, 1e-4, None),
              'r-|', lw=1.5, ms=6, markeredgewidth=1.2)
    ax.set_xlabel("Cascade size s", fontsize=9)
    ax.set_ylabel("P(S ≥ s)", fontsize=9)
    ax.set_title("CCDF of cascade sizes\n(power-law tail = SOC)", fontsize=9)
    ax.grid(True, which='both', alpha=0.25)

    # ── (Centre) Degree distribution of tumour sub-network ───────
    ax = axes[1]
    cancer_nodes = [v for v in G.nodes() if state[v] == CANCEROUS]
    if cancer_nodes:
        deg_seq          = [G.degree(v) for v in cancer_nodes]
        unique_k, cnt_k  = np.unique(deg_seq, return_counts=True)
        prob_k           = cnt_k / cnt_k.sum()
        ax.loglog(unique_k.astype(float), prob_k, 's',
                  color='navy', ms=5, alpha=0.8)
        # Power-law visual guide
        k_fit  = np.linspace(1, float(unique_k.max()), 100)
        ax.loglog(k_fit, k_fit**-3 / k_fit[0]**-3 * prob_k[0],
                  'r--', lw=1.2, label='k⁻³ guide', alpha=0.6)
        ax.legend(fontsize=8)
    ax.set_xlabel("Degree k", fontsize=9)
    ax.set_ylabel("P(k)", fontsize=9)
    ax.set_title("Degree distribution of tumour\nsub-network (scale-free?)", fontsize=9)
    ax.grid(True, which='both', alpha=0.25)

    # ── (Right) Rolling Hurst exponent ───────────────────────────
    ax = axes[2]
    H_vals = rolling_hurst(tumour_counts, window=40)
    ax.plot(np.arange(len(H_vals)), H_vals,
            color='steelblue', lw=1.3, alpha=0.85)
    ax.axhline(0.5, color='dimgray', ls='--', lw=1.3, label='H=0.5 (random)')
    h_mean = float(np.mean(H_vals))
    ax.axhline(h_mean, color='firebrick', ls=':', lw=1.2,
               label=f'H̄={h_mean:.2f}')
    ax.set_ylim(0.35, 1.05)
    ax.set_xlabel("Window index", fontsize=9)
    ax.set_ylabel("H", fontsize=9)
    ax.set_title("Rolling Hurst exponent\n(window=40 steps)", fontsize=9)
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.25)

    plt.tight_layout()
    save_path = os.path.join(OUT_DIR, "figure2_soc_signatures.png")
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.show()
    print(f"  ✓ Figure 2 saved → {save_path}")
    plt.close()


# ═══════════════════════════════════════════════
# 9.  FIGURE 3 — Network final state
# ═══════════════════════════════════════════════
def plot_figure3(G, state):

    COLOR = {HEALTHY: 'limegreen', CANCEROUS: 'firebrick', NECROTIC: 'dimgray'}
    LABEL = {HEALTHY: 'Healthy',   CANCEROUS: 'Cancerous', NECROTIC: 'Necrotic'}

    node_colors = [COLOR[state[v]] for v in G.nodes()]
    degrees     = np.array([G.degree(v) for v in G.nodes()])
    node_sizes  = 18 + 3.5 * degrees   # hubs appear larger

    pos = nx.spring_layout(G, seed=SEED, k=0.32)

    fig, ax = plt.subplots(figsize=(10, 8.5))
    fig.patch.set_facecolor('white')

    # Edges (very transparent)
    nx.draw_networkx_edges(G, pos, ax=ax,
                           alpha=0.07, edge_color='gray', width=0.5)

    # Nodes — draw by state so legend works cleanly
    for s_val in [HEALTHY, CANCEROUS, NECROTIC]:
        nlist = [v for v in G.nodes() if state[v] == s_val]
        sizes = [node_sizes[v] for v in nlist]
        nx.draw_networkx_nodes(G, pos, nodelist=nlist,
                               node_color=COLOR[s_val],
                               node_size=sizes, ax=ax,
                               label=LABEL[s_val], alpha=0.88)

    ax.legend(loc='upper left', framealpha=0.9, fontsize=10, markerscale=1.3)
    ax.set_title("Tumour network: final state\n(Barabási–Albert topology)",
                 fontsize=12, fontweight='bold')
    ax.axis('off')

    plt.tight_layout()
    save_path = os.path.join(OUT_DIR, "figure3_network_final_state.png")
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.show()
    print(f"  ✓ Figure 3 saved → {save_path}")
    plt.close()


# ═══════════════════════════════════════════════
# MAIN DRIVER
# ═══════════════════════════════════════════════
if __name__ == "__main__" or True:   # ← True ensures this runs in Jupyter too

    print("=" * 58)
    print("  Cancer Tumour Growth — Complex Network Simulation")
    print("=" * 58)

    # ── Step 1: Build network ──────────────────────────────────
    print(f"\n[1/4] Building Barabási–Albert tissue network "
          f"(N={N}, m={M_BA}, seed={SEED}) ...")
    G       = build_tissue_network()
    mean_d  = np.mean([d for _, d in G.degree()])
    max_d   = max(d for _, d in G.degree())
    print(f"      Mean degree : {mean_d:.2f}  |  Max degree : {max_d}")

    # ── Step 2: Run simulation ─────────────────────────────────
    print(f"\n[2/4] Running tumour growth simulation (T_max={T_MAX}) ...")
    (tumour_counts, avalanche_sizes, mean_degrees,
     state, final_mutation, G) = run_simulation(G)

    t_end  = int(tumour_counts[-1, 0])
    n_av   = len(avalanche_sizes)
    print(f"      Terminated at t = {t_end}")
    print(f"      Avalanche events recorded : {n_av}")
    print(f"      Max single cascade size   : {int(avalanche_sizes.max())} cells")

    slope, _, r2, *_ = fit_power_law(avalanche_sizes)
    print(f"      Power-law exponent α = {abs(slope):.2f}  (R²={r2:.2f})")

    H_global = hurst_rs(np.diff(tumour_counts[:, 1].astype(float)))
    print(f"      Global Hurst exponent H ≈ {H_global:.2f}")

    # ── Step 3: Percolation analysis ───────────────────────────
    print(f"\n[3/4] Running percolation analysis "
          f"({PERC_REPS} reps × {len(K_VALUES)} k-values) ...")
    cascade_fractions = run_percolation_analysis()
    grad   = np.gradient(cascade_fractions)
    kc_idx = int(np.argmax(grad))
    print(f"      Estimated percolation threshold kc ≈ {K_VALUES[kc_idx]:.1f}")

    # ── Step 4: Plot all figures ────────────────────────────────
    print(f"\n[4/4] Generating figures (saved to: {OUT_DIR}) ...")
    plot_figure1(tumour_counts, avalanche_sizes, mean_degrees, cascade_fractions)
    plot_figure2(G, avalanche_sizes, tumour_counts, state)
    plot_figure3(G, state)

    print("\n" + "=" * 58)
    print("  All done!  3 figures saved to:", OUT_DIR)
    print("=" * 58)